host: 0.0.0.0
port: 7070

sr: 22050
asr_model_name: stt_en_fastconformer_transducer_large
tts_model_name: [tts_en_fastpitch, tts_en_hifigan]

chatgpt_name: ft:gpt-3.5-turbo
openai_key: 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
prompt_base: 'Answer the following question within 512 characters: '